### ISSUE TITLE
SSL certificate on andy.edinborough.org has expired

### ISSUE THREAD

**Issue by gregsadetsky** [andyedinborough/stress-css#14]
https://andy.edinborough.org/CSS-Stress-Testing-and-Performance-Profiling is popping up a warning as the SSL certificate for andy.edinborough.org has expired

thanks!

**Comment by andyedinborough** [comment]
Sorry about that, and thanks for letting me know!  Looks like the certificate renewed, but nginx didn't pick it up.  Restarting nginx resolved it.

**Comment by gregsadetsky** [comment]
I'm afraid that the SSL certificate has once again expired (it just did, about 24 hours ago)

https://www.ssllabs.com/ssltest/analyze.html?d=andy.edinborough.org&hideResults=on&latest

Cheers
