### ISSUE TITLE
More accurate cross-browser timing

### ISSUE THREAD

**Issue by mathiasbynens** [andyedinborough/stress-css#2]
Just a heads up — it looks like you’re using [Pattern A](http://calendar.perfplanet.com/2010/bulletproof-javascript-benchmarks/) to measure the time interval. This may not be accurate (enough) across browsers and platforms. See the link I provided for more information, and feel free to check out [the Benchmark.js source code](https://github.com/mathiasbynens/Benchmark.js) for some alternatives.

**Comment by andyedinborough** [comment]
Actually I am using pattern B.  The function below runs once per class.  It records the time at the beginning and then at the end--so the time is recorded over the course of _n_ (`times`) tests.

```
function stress(state, times, finish) {
    var now = +new Date, //the test is starting
      work = function () {
          window.scrollBy(0, times % 2 == 0 ? 100 : -100);
      };
    times *= 2; //each test consists of scrolling down, and then back up

    bind(window, 'scroll.stressTest', function () {
        if (--times && !state.cancel) {
            setTimeout(work, 0);
        } else {
            unbind(window, 'scroll.stressTest');
            finish((+new Date) - now); //the test is over
        }
    });

    work();
}
```

**Comment by mathiasbynens** [comment]
Well the same applies for Pattern B, really. Check out the “Inaccurate millisecond timers” section in the article for the most poignant problem.
