### ISSUE TITLE
escape keypress bug

### ISSUE THREAD

**Issue by gmoulin** [andyedinborough/stress-css#3]
Hi,
i was stressing the css of my pet project and i remarked that the escape press did nothing.

I have in the project script a listener for escape key press like :

```
$('html').unbind('keypress').keypress(function(e){
    // ESCAPE key pressed
    if( e.keyCode == 27 ){
        console.log('escape pressed');
                    //...
            }
    });
```

Since the bookmarklet "fire" after the unbind() it should not interfer.

**Comment by andyedinborough** [comment]
I can't seem to replicate this issue.  Can you show me an example page, and tell me what browser you're using?
