### ISSUE TITLE
Test stops if Y axis scrollbar dissappears

### ISSUE THREAD

**Issue by beneverard** [andyedinborough/stress-css#4]
Great little script, I did notice however the following problem:

1) Tested page has enough content to show the Y axis scrollbar
2) Stress script removes a class, content shrinks (font-size significantly reduced, for example)
3) Page no longer has Y axis scrollbar and thus stress script stops

I got around this by resizing my browser a bit, issue occurs on http://beneverard.co.uk on a 21" widescreen running at 1680x1050 resolution, would certainly occur on much smaller resolutions too.

**Comment by andyedinborough** [comment]
Yeah, I was aware of that bug.  I just haven't gotten to fixing it yet.  The best idea I could think of was adding a bottom padding to the body element until there was at least 200px of scroll.  Something like : body.style.paddingBottom = window.height - body.offsetHeight + 200.

**Comment by andyedinborough** [comment]
So the code needed to do it was simpler: `document.body.style.marginBottom = window.screen.height + 'px';`.  It's checked in now.  The margin then resets after the test.
