### ISSUE TITLE
Text is unreadable as text color is set by website's stylesheet, not bookmarklet

### ISSUE THREAD

**Issue by wjcrowcroft** [andyedinborough/stress-css#5]
Hey, Great little bookmarklet!

One issue - when testing it on a recent project, because the site employs white text on a dark background, it's impossible to read the test progress while it's happening, or the results afterwards - the bookmarklet displays white text on a white background.

Easily fixed by applying a `style="color#444"` attribute on the bookmarklet's text output.

Cheers!

**Comment by duckinator** [comment]
Same issue. Try it on http://stage.duckinator.net if you want an example (uses white text)

**Comment by andyedinborough** [comment]
Thanks for the feedback, I've added that to the code.
